services:
  backend:
    image: ${LOCAL_IMAGE_NAME}
    ports:
      - "8080:8080"
    environment:
      - TEST_RUN=True
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_DEFAULT_REGION=us-east-1
      - PREDICTIONS_STREAM_NAME=ride_predictions
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}